version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderdb

  database:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongo-data:

networks:
  default:
    name: mqtt5-network
