# docker-compose.yml
version: '3.8'

services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: orderdb
